variables:
  UV_VERSION: 0.9.10
  PYTHON_VERSION: 3.12
  BASE_LAYER: trixie-slim
  UV_CACHE_DIR: .uv-cache
  UV_SYSTEM_PYTHON: 1
stages:
  - test

pytest:
  before_script:
  - apt-get update -qq && apt-get install -y -qq git git-lfs
  - git lfs pull
  - git submodule update --init --recursive  
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv sync
    - uv run nox -s test_dev
  only:
    - merge_requests
    - main
  allow_failure: true
