dataloaders:
  loaders:
    - name: comma10k
      type: image_dir
      path: examples/data/comma10k_sample/imgs
      load_batch_size: 10
      decode: img_bytes

transformations:
  outputs:
    path: examples/outputs/{selection}/ledger.parquet
    write_images: true
    images_dir: examples/outputs/{selection}/payloads
    flush_batch_size: 128
  transformations:
    - name: horizontal_flip
      type: horizontal_flip
    - name: crop_resize
      type: crop_resize
      fraction: 0.4